services:
  - type: web
    name: herbmed-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput --clear && python manage.py migrate && python manage.py restore_original_images && python manage.py create_superuser"
    startCommand: "gunicorn loginSignup.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: herbmed-db
    databaseName: herbmed
    user: herbmed_user